keys:
  - &vm age138cx5xxndervgswvzk78nstf0kctfjydxlephpqny0dtyezg8vvsjmu3pk
  - &vmiss-us-1 age1dy6qammgzzngncx6fpcttzy9ny2p250ph84hlnsp0rv7ta5xy9gqnujt97
  - &locvps-hk-1 age1kpmn99u6q59gpk8qq9ll54070yc2yhd3ms7jfvuk263vzkv9pepqghhx3u

creation_rules:
  - path_regex: ^secrets/[^/]+\.yaml$
    key_groups:
      - age: [*vm, *vmiss-us-1, *locvps-hk-1]
